spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123
    url: jdbc:mysql://localhost:3306/zyf
  session:
    timeout: 86400
    #Session失效时间
server:
  port: 8080
  servlet:
    context-path: /api
    #指定接口全局路径前缀、与前端对接
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    #关闭mp自动驼峰、下划线映射
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
      #开启mp的逻辑删除功能